/* AUTO-GENERATED by `pnpm calibrate` — do not edit by hand.
 * No human corpus yet; thresholds are first-principles priors.
 * generated: 2026-08-23
 */
import type { DeepPartial, BenchConfig } from "@/lib/core/config";

export const CALIBRATION = {
  "basis": "prior",
  "generatedAt": "2026-08-23",
  "fprTarget": 0.001,
  "humanCorpus": {
    "files": 0,
    "swipes": 0,
    "subjects": [],
    "inputs": {}
  },
  "perFeature": {
    "jitter": {
      "label": "motor-noise jitter (px)",
      "direction": "low",
      "target": "naive",
      "auc": null,
      "note": "no human corpus — threshold left at prior"
    },
    "white": {
      "label": "Δ⁴/Δ² whiteness",
      "direction": "high",
      "target": "generative-iid",
      "auc": null,
      "note": "no human corpus — threshold left at prior"
    },
    "wamp": {
      "label": "implied noise σ (px)",
      "direction": "high",
      "target": "generative-iid",
      "auc": null,
      "note": "no human corpus — threshold left at prior"
    },
    "peakT": {
      "label": "velocity-peak position",
      "direction": "low",
      "target": "naive",
      "auc": null,
      "note": "no human corpus — threshold left at prior"
    },
    "dur": {
      "label": "swipe duration (ms)",
      "direction": "low",
      "target": "naive",
      "auc": null,
      "note": "no human corpus — threshold left at prior"
    }
  },
  "aucMatrix": {
    "jitter": {
      "naive": null,
      "replay": null,
      "generative-iid": null,
      "generative-organic": null,
      "stealth": null
    },
    "white": {
      "naive": null,
      "replay": null,
      "generative-iid": null,
      "generative-organic": null,
      "stealth": null
    },
    "wamp": {
      "naive": null,
      "replay": null,
      "generative-iid": null,
      "generative-organic": null,
      "stealth": null
    },
    "peakT": {
      "naive": null,
      "replay": null,
      "generative-iid": null,
      "generative-organic": null,
      "stealth": null
    },
    "dur": {
      "naive": null,
      "replay": null,
      "generative-iid": null,
      "generative-organic": null,
      "stealth": null
    }
  },
  "note": "No human corpus recorded yet (need ≥50 swipes). Thresholds remain first-principles priors. Record a corpus with recorder/index.html, drop it in corpus/, and re-run `pnpm calibrate`."
} as const;

export const CALIBRATED_THRESHOLDS: DeepPartial<BenchConfig["detector"]> = {};
